spring.application.name=mycoolapp
#Overriding the default port to 8181
server.port=8181
coach.name=Mickey Mouse
team.name=The Mouse Crew

#By defaults only /health is exposed in our actuator
#So expose heath,info now
#management.endpoints.web.exposure.include=health,info
#management.endpoints.web.exposure.include=health,info,beans,mappings
#Enable all actuator endpoints exposed
management.endpoints.web.exposure.include=*

management.info.env.enabled=true

#configuring what info should look like
info.app.name=My Super Cool App
info.app.description=A crazy and fun app... Hoolaa
info.app.version=1.0.0
#To exclude some actuator endpoints we use the exclude property and set them
management.endpoints.web.exposure.exclude=health, info

#Overriding default user name and generated password from spring security
spring.security.user.name=faruq
spring.security.user.password=password

