spring.application.name=mycoolapp
#Overriding the default port to 8181
server.port=8181
coach.name=Mickey Mouse
team.name=The Mouse Crew

#By defaults only /health is exposed in our actuator
#So expose info now
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
