spring.application.name=mycoolapp
#Overriding the default port 8080 to 8181
server.port=8181

#DEFINE CUSTOM PROPERTIES
coach.name=FARUQ HAMEED
team.name=Team Faruq

#overriding default context path of the application(must always start with / and not end with /
server.servlet.context-path=/mycoolapp

#Default session timeout is 30mins
server.servlet.session.timeout=1m

#Overrideding default basepath for actuator
management.endpoints.web.base-path=/act




