spring.application.name=employeemanagement

#JDBC properties

spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# configure swagger doc custom path
#springdoc.swagger-ui.path=/api-ui.html

#configure custom path for api docs
#springdoc.api-docs.path=/api/docs